name: CI Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Ckeckout code
        uses: actions/checkout@v5

      - name: Set Up node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependiencies
        run: npm Install

      - name: Run tests
        run: npm test  
